// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkpdgnbqnpqpwwwsgift.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrcGRnbmJxbnBxcHd3d3NnaWZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NTUzMDEsImV4cCI6MjA3MjAzMTMwMX0.j6Iaq_UKFlSZ8LOW45QWXUDcArh7fjCYjhpQMIxCuGc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});